#---------------------------------------------------------------
#                         VOLUME CLAIMS
#---------------------------------------------------------------
#DATA
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sentry
  name: clickhouse-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---

#LOGS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sentry
  name: clickhouse-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
