#---------------------------------------------------------------
#                         VOLUME CLAIMS
#---------------------------------------------------------------
#DATA
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitor
  name: clickhouse-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---

#LOGS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitor
  name: clickhouse-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
