#---------------------------------------------------------------
#                         VOLUME CLAIMS
#---------------------------------------------------------------
#WEB DATA
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sentry
  name: sentry-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
