apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cron
  name: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cron
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cron
    spec:
      containers:
        - args:
            - run
            - cron
          env:
            - name: SENTRY_CONF
              value: /etc/sentry
            - name: SNUBA
              value: http://snuba-api:1218
          image: sentry-onpremise-local
          name: cron
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: sentry-data
            - mountPath: /etc/sentry
              name: cron-claim1
      restartPolicy: Always
      volumes:
        - name: sentry-data
          persistentVolumeClaim:
            claimName: sentry-data
        - name: cron-claim1
          persistentVolumeClaim:
            claimName: cron-claim1
status: {}
