apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: SENTRY_CONF
              value: /etc/sentry
            - name: SNUBA
              value: http://snuba-api:1218
          image: sentry-onpremise-local
          name: web
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: sentry-data
            - mountPath: /etc/sentry
              name: web-claim1
      restartPolicy: Always
      volumes:
        - name: sentry-data
          persistentVolumeClaim:
            claimName: sentry-data
        - name: web-claim1
          persistentVolumeClaim:
            claimName: web-claim1
status: {}
