apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: smtp
  name: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smtp
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: smtp
    spec:
      containers:
        - image: tianon/exim4
          name: smtp
          resources: {}
          volumeMounts:
            - mountPath: /var/spool/exim4
              name: sentry-smtp
            - mountPath: /var/log/exim4
              name: sentry-smtp-log
      restartPolicy: Always
      volumes:
        - name: sentry-smtp
          persistentVolumeClaim:
            claimName: sentry-smtp
        - name: sentry-smtp-log
          persistentVolumeClaim:
            claimName: sentry-smtp-log
status: {}
