apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: relay
  name: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: relay
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: relay
    spec:
      containers:
        - image: relay
          name: relay
          resources: {}
          volumeMounts:
            - mountPath: /work/.relay
              name: relay-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: relay-claim0
          persistentVolumeClaim:
            claimName: relay-claim0
            readOnly: true
status: {}
