#---------------------------------------------------------------
#                             SERVICES
#---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  namespace: monitor
  name: cp-kafka
spec:
  type: NodePort
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    instance: cp-kafka
---

#---------------------------------------------------------------
#                           WORKLOADS
#---------------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: monitor
  name: cp-kafka
  labels:
    instance: cp-kafka

spec:
  serviceName: cp-kafka
  selector:
    matchLabels:
      instance: cp-kafka

  #Initial replicas
  replicas: 1

  #Template
  template:
    metadata:
      labels:
        instance: cp-kafka

    spec:
      initContainers:
        - name: cp-kafka-fs-permission
          image: confluentinc/cp-kafka:6.0.1
          imagePullPolicy: IfNotPresent

          command: ["chown", "-R", "1000:1000", "/var/lib/kafka"]

          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: cp-kafka-data
            - mountPath: /var/lib/kafka/log
              name: cp-kafka-log

          securityContext:
            runAsUser: 0

      containers:
        - name: cp-kafka
          image: confluentinc/cp-kafka:6.0.1
          imagePullPolicy: IfNotPresent

#          resources:
#            requests:
#              memory: "1024Mi"

          envFrom:
            - configMapRef:
                name: cp-kafka

          ports:
            - containerPort: 9092

          command:
            - sh
            - -exc
            - |
              rm -Rf /var/lib/kafka/data/lost+found || true

              export KAFKA_BROKER_ID=${HOSTNAME##*-}
              export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=DEFAULT:PLAINTEXT
              export KAFKA_LISTENERS=DEFAULT://0.0.0.0:9092
              export KAFKA_ADVERTISED_LISTENERS=DEFAULT://${HOSTNAME}.cp-kafka.sentry.svc.cluster.local:9092
              export KAFKA_INTER_BROKER_LISTENER_NAME=DEFAULT

              exec /etc/confluent/docker/run

          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: cp-kafka-data
            - mountPath: /var/lib/kafka/log
              name: cp-kafka-log

  volumeClaimTemplates:
    - metadata:
        namespace: monitor
        name: cp-kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
    - metadata:
        namespace: monitor
        name: cp-kafka-log
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 128Mi
