#---------------------------------------------------------------
#                             SERVICES
#---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  namespace: monitor
  name: postgresql
spec:
  type: ExternalName
  externalName: your-external-postgrsql.domain.com
  ports:
    - port: 5432
