#---------------------------------------------------------------
#                             SERVICES
#---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  namespace: sentry
  name: redis
spec:
  type: NodePort
  ports:
    - port: 6379
  selector:
    instance: redis
---

#---------------------------------------------------------------
#                           WORKLOADS
#---------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sentry
  name: redis
  labels:
    instance: redis
spec:
  selector:
    matchLabels:
      instance: redis

  #Initial replicas
  replicas: 1

  #Replacement strategy
  strategy:
    type: Recreate

  #Template
  template:
    metadata:
      labels:
        instance: redis

    spec:
      containers:
        - name: redis
          image: redis:5
          imagePullPolicy: IfNotPresent

#          resources:
#            requests:
#              memory: "512Mi"

          ports:
            - containerPort: 6379
