#---------------------------------------------------------------
#                             SERVICES
#---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  namespace: monitor
  name: redis
spec:
  type: NodePort
  ports:
    - port: 6379
  selector:
    instance: redis
---

#---------------------------------------------------------------
#                           WORKLOADS
#---------------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: monitor
  name: redis
  labels:
    instance: redis
spec:
  selector:
    matchLabels:
      instance: redis

  #Initial replicas
  replicas: 1

  #Replacement strategy
  strategy:
    type: Recreate

  #Template
  template:
    metadata:
      labels:
        instance: redis

    spec:
      initContainers:
        - name: redis-disable-thp #Transparent Huge Pages (THP)
          image: redis:5
          imagePullPolicy: IfNotPresent

          command: ["sh", "-c", "echo never > /host-sys/kernel/mm/transparent_hugepage/enabled"]

          volumeMounts:
            - name: host-sys
              mountPath: /host-sys

      containers:
        - name: redis
          image: redis:5
          imagePullPolicy: IfNotPresent

#          resources:
#            requests:
#              memory: "512Mi"

          ports:
            - containerPort: 6379

      volumes:
        - name: host-sys
          hostPath:
            path: /sys
