##---------------------------------------------------------------
##                           WORKLOADS
##---------------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: sentry
  name: sentry-cron
  labels:
    instance: sentry-cron
spec:
  serviceName: sentry-cron
  selector:
    matchLabels:
      instance: sentry-cron

  #Initial replicas
  replicas: 1

  #Template
  template:
    metadata:
      labels:
        instance: sentry-cron
    spec:
      containers:
        - name: sentry-cron
          image: getsentry/sentry:20.10.1
          imagePullPolicy: IfNotPresent

#          resources:
#            requests:
#              memory: "150Mi"

          args: ["run", "cron"]

          envFrom:
            - configMapRef:
                name: sentry

          volumeMounts:
            - name: sentry-data
              mountPath: /data

      volumes:
        - name: sentry-data
          persistentVolumeClaim:
            claimName: sentry-data
