#---------------------------------------------------------------
#                             SERVICES
#---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  namespace: sentry
  name: sentry-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
  selector:
    instance: sentry-web
---

#---------------------------------------------------------------
#                           WORKLOADS
#---------------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: sentry
  name: sentry-web
  labels:
    instance: sentry-web
spec:
  serviceName: sentry-web
  selector:
    matchLabels:
      instance: sentry-web

  #Initial replicas
  replicas: 1

  #Template
  template:
    metadata:
      labels:
        instance: sentry-web
    spec:
      containers:
        - name: sentry-web
          image: getsentry/sentry:20.11.1
          imagePullPolicy: IfNotPresent

#          resources:
#            requests:
#              memory: "150Mi"

          ports:
            - containerPort: 9000

          readinessProbe:
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 1
            httpGet:
              port: 9000
              path: /_health/

          envFrom:
            - configMapRef:
                name: sentry

          volumeMounts:
            - name: sentry-data
              mountPath: /data

      volumes:
        - name: sentry-data
          persistentVolumeClaim:
            claimName: sentry-data
