#---------------------------------------------------------------
#                             SERVICES
#---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  namespace: sentry
  name: snuba-api
spec:
  type: NodePort
  ports:
    - port: 1218
  selector:
    instance: snuba-api
---

##---------------------------------------------------------------
##                           WORKLOADS
##---------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sentry
  name: snuba-api
  labels:
    instance: snuba-api
spec:
  selector:
    matchLabels:
      instance: snuba-api

  #Initial replicas
  replicas: 1

  #Template
  template:
    metadata:
      labels:
        instance: snuba-api
    spec:
      containers:
        - name: snuba-api
          image: getsentry/snuba:20.11.1
          imagePullPolicy: IfNotPresent

#          resources:
#            requests:
#              memory: "150Mi"

          ports:
            - containerPort: 1218

          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 1218
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 1218
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2

          command: ["snuba", "api"]

          envFrom:
            - configMapRef:
                name: snuba
