apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - run
            - worker
          env:
            - name: SENTRY_CONF
              value: /etc/sentry
            - name: SNUBA
              value: http://snuba-api:1218
          image: sentry-onpremise-local
          name: worker
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: sentry-data
            - mountPath: /etc/sentry
              name: worker-claim1
      restartPolicy: Always
      volumes:
        - name: sentry-data
          persistentVolumeClaim:
            claimName: sentry-data
        - name: worker-claim1
          persistentVolumeClaim:
            claimName: worker-claim1
status: {}
