apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: snuba-replacer
  name: snuba-replacer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snuba-replacer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: snuba-replacer
    spec:
      containers:
        - args:
            - replacer
            - --storage
            - events
            - --auto-offset-reset=latest
            - --max-batch-size
            - "3"
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: DEFAULT_BROKERS
              value: kafka:9092
            - name: REDIS_HOST
              value: redis
            - name: SNUBA_SETTINGS
              value: docker
            - name: UWSGI_DISABLE_LOGGING
              value: "true"
            - name: UWSGI_MAX_REQUESTS
              value: "10000"
          image: snuba-replacer
          name: snuba-replacer
          resources: {}
      restartPolicy: Always
status: {}
