apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: snuba-api
  name: snuba-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snuba-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: snuba-api
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: DEFAULT_BROKERS
              value: kafka:9092
            - name: REDIS_HOST
              value: redis
            - name: SNUBA_SETTINGS
              value: docker
            - name: UWSGI_DISABLE_LOGGING
              value: "true"
            - name: UWSGI_MAX_REQUESTS
              value: "10000"
          image: snuba-api
          name: snuba-api
          resources: {}
      restartPolicy: Always
status: {}
