#---------------------------------------------------------------
#                         CONFIGURATION
#---------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: sentry
  name: cp-zookeeper
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
  CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: "WARN"
  ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL: "WARN"