#---------------------------------------------------------------
#                         CONFIGURATION
#---------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: sentry
  name: postgresql
data:
  POSTGRES_DB: sentry
  POSTGRES_USER: sentry
  POSTGRES_PASSWORD: sentry

  PGDATA: /data/postgresql/12