#---------------------------------------------------------------
#                         CONFIGURATION
#---------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: sentry
  name: sentry
data:
  SENTRY_SINGLE_ORGANIZATION: "true"
  #MUST BE CHANGED with docker run --rm getsentry/sentry:20.11.1 config generate-secret-key
  SENTRY_SECRET_KEY: "gz)x*&-n5wl3yn#=kf1sud7-z@)w9z8jwyl9+dk5hpr(9d6cia"
  SENTRY_EVENT_RETENTION_DAYS: "90"

  SENTRY_POSTGRES_HOST: postgresql
  SENTRY_POSTGRES_PORT: "5432"
  SENTRY_DB_USER: sentry
  SENTRY_DB_PASSWORD: sentry
  SENTRY_DB_NAME: sentry

  SENTRY_REDIS_HOST: "redis"
  SENTRY_REDIS_PORT: "6379"

  SENTRY_EMAIL_HOST: "localhost"
  SENTRY_EMAIL_PORT: "25"
  SENTRY_EMAIL_USER: ""
  SENTRY_EMAIL_PASSWORD: ""
  SENTRY_EMAIL_USE_TLS: "false"
  SENTRY_SERVER_EMAIL: no-reply@sentry.com

  SENTRY_ADMIN_USER_EMAIL: admin@sentry.com
  SENTRY_ADMIN_USER_PASSWORD: sentry

  SLACK_CLIENT_ID: "000"
  SLACK_CLIENT_SECRET: "000"
  SLACK_VERIFICATION_TOKEN: "000"

  GITHUB_APP_ID: ''
  GITHUB_API_SECRET: ''
  SENTRY_GITHUB_APP_ID: ''
  SENTRY_GITHUB_APP_CLIENT_ID: ''
  SENTRY_GITHUB_APP_CLIENT_SECRET: ''
  SENTRY_GITHUB_APP_WEBHOOK_SECRET: ''
  SENTRY_GITHUB_APP_PRIVATE_KEY: ''

  SNUBA: 'http://snuba-api:1218'
