#---------------------------------------------------------------
#                         CONFIGURATION
#---------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: sentry
  name: sentry-relay
data:
  config.yml: |-
    relay:
      upstream: "http://sentry-web:9000/"
      host: 0.0.0.0
      port: 3000
    logging:
      level: WARN
    processing:
      enabled: true
      kafka_config:
        - {name: "bootstrap.servers", value: "cp-kafka.sentry.svc.cluster.local:9092"}
        - {name: "message.max.bytes", value: 50000000} #50MB or bust
      redis: redis://redis.sentry.svc.cluster.local:6379
