#---------------------------------------------------------------
#                         CONFIGURATION
#---------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: sentry
  name: snuba
data:
  SNUBA_SETTINGS: "docker"

  UWSGI_MAX_REQUESTS: "10000"
  UWSGI_DISABLE_LOGGING: "true"

  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_SINGLE_NODE: "true"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  DEFAULT_BROKERS: "cp-kafka:9092"
