#---------------------------------------------------------------
#                             JOB
#---------------------------------------------------------------
apiVersion: batch/v1
kind: Job
metadata:
  namespace: sentry
  name: cp-kafka
spec:
  template:
    spec:
      containers:
        - name: cp-kafka-job
          image: confluentinc/cp-kafka:6.0.0
          imagePullPolicy: IfNotPresent

          command:
            - sh
            - -exc
            - |
              kafka-topics --create --topic ingest-attachments --bootstrap-server cp-kafka:9092 || true
              kafka-topics --create --topic ingest-transactions --bootstrap-server cp-kafka:9092 || true
              kafka-topics --create --topic ingest-events --bootstrap-server cp-kafka:9092 || true

      restartPolicy: Never
  backoffLimit: 6
  ttlSecondsAfterFinished: 120
