#---------------------------------------------------------------
#                             JOB
#---------------------------------------------------------------
apiVersion: batch/v1
kind: Job
metadata:
  namespace: sentry
  name: postgresql
spec:
  template:
    spec:
      containers:
        - name: postgresql-job
          image: postgres:12
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: sentry
          env:
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sentry
                  key: SENTRY_DB_PASSWORD

          command: ["/bin/sh"]
          args: ["-c", "createdb -h postgresql -U $(SENTRY_DB_USER) $(SENTRY_DB_NAME) || true"]

      restartPolicy: Never
  backoffLimit: 6
  ttlSecondsAfterFinished: 120
