#---------------------------------------------------------------
#                             JOB
#---------------------------------------------------------------
apiVersion: batch/v1
kind: Job
metadata:
  namespace: sentry
  name: sentry
spec:
  template:
    spec:
      containers:
        - name: sentry-job
          image: getsentry/sentry:20.11.1
          imagePullPolicy: IfNotPresent

          command:
            - sh
            - -exc
            - |
              sentry upgrade --noinput --verbosity 1
              sentry createuser --no-input --email $(SENTRY_ADMIN_USER_EMAIL) --superuser --password $(SENTRY_ADMIN_USER_PASSWORD) || true

          envFrom:
            - configMapRef:
                name: sentry

      restartPolicy: Never
  backoffLimit: 6
  ttlSecondsAfterFinished: 350
