apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: symbolicator-cleanup
  name: symbolicator-cleanup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbolicator-cleanup
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: symbolicator-cleanup
    spec:
      containers:
        - args:
            - 55 23 * * * gosu symbolicator symbolicator cleanup
          image: symbolicator-cleanup-onpremise-local
          name: symbolicator-cleanup
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: sentry-symbolicator
      restartPolicy: Always
      volumes:
        - name: sentry-symbolicator
          persistentVolumeClaim:
            claimName: sentry-symbolicator
status: {}
