apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: symbolicator
  name: symbolicator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbolicator
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: symbolicator
    spec:
      containers:
        - args:
            - run
            - -c
            - /etc/symbolicator/config.yml
          image: symbolicator
          name: symbolicator
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: sentry-symbolicator
            - mountPath: /etc/symbolicator
              name: symbolicator-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: sentry-symbolicator
          persistentVolumeClaim:
            claimName: sentry-symbolicator
        - name: symbolicator-claim1
          persistentVolumeClaim:
            claimName: symbolicator-claim1
            readOnly: true
status: {}
